version: '3.9'
services:
  db:
    image: postgres:15.0-alpine
    container_name: db-postgre
    restart: always
    ports:
      - '5435:5432'
    env_file:
      - ./backend/db.local.env
    volumes:
      - ./postgres_data:/var/lib/postgresql/data/
